<a href="https://colab.research.google.com/github/harshkrr/gitbranchtest/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

In [ ]:
import sklearn
print(sklearn.__version__)

0.22.2.post1


## **Auto Summerizing Text**

In [ ]:
import urllib3
from bs4 import BeautifulSoup

## **Vectorize text as a bag of words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
train_test = ["A bird in han d is worth two in the bush.",
              "Good things come to those who wait.",
              "These watches cost $1500!",
              "There are other fish in the sea.",
              "The ball is in your court.",
              "Mr. Smith goes to Washigton.",
              "Doiggle Hower M.C."
              ]
count_vectorizer = CountVectorizer()

In [ ]:
count_vectorizer.fit(train_test)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
count_vectorizer.get_feature_names()

['1500',
 'are',
 'ball',
 'bird',
 'bush',
 'come',
 'cost',
 'court',
 'doiggle',
 'fish',
 'goes',
 'good',
 'han',
 'hower',
 'in',
 'is',
 'mr',
 'other',
 'sea',
 'smith',
 'the',
 'there',
 'these',
 'things',
 'those',
 'to',
 'two',
 'wait',
 'washigton',
 'watches',
 'who',
 'worth',
 'your']

In [ ]:
count_vectorizer.get_stop_words()

In [ ]:
count_vectorizer.vocabulary_

{'1500': 0,
 'are': 1,
 'ball': 2,
 'bird': 3,
 'bush': 4,
 'come': 5,
 'cost': 6,
 'court': 7,
 'doiggle': 8,
 'fish': 9,
 'goes': 10,
 'good': 11,
 'han': 12,
 'hower': 13,
 'in': 14,
 'is': 15,
 'mr': 16,
 'other': 17,
 'sea': 18,
 'smith': 19,
 'the': 20,
 'there': 21,
 'these': 22,
 'things': 23,
 'those': 24,
 'to': 25,
 'two': 26,
 'wait': 27,
 'washigton': 28,
 'watches': 29,
 'who': 30,
 'worth': 31,
 'your': 32}

In [ ]:
transformed_vector = count_vectorizer.transform(train_test)

In [ ]:
print(transformed_vector.toarray())

[[0 0 0 1 1 0 0 0 0 0 0 0 1 0 2 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
count_vectorizer.inverse_transform(transformed_vector)

[array(['bird', 'bush', 'han', 'in', 'is', 'the', 'two', 'worth'],
       dtype='<U9'),
 array(['come', 'good', 'things', 'those', 'to', 'wait', 'who'],
       dtype='<U9'),
 array(['1500', 'cost', 'these', 'watches'], dtype='<U9'),
 array(['are', 'fish', 'in', 'other', 'sea', 'the', 'there'], dtype='<U9'),
 array(['ball', 'court', 'in', 'is', 'the', 'your'], dtype='<U9'),
 array(['goes', 'mr', 'smith', 'to', 'washigton'], dtype='<U9'),
 array(['doiggle', 'hower'], dtype='<U9')]

## **Vectorize text as a bag of n grams**

In [ ]:
n_gram_vectorizer = CountVectorizer(ngram_range=(2,2))

In [ ]:
transformed_vector_n = n_gram_vectorizer.fit_transform(train_test)

In [ ]:
n_gram_vectorizer.vocabulary_

{'are other': 0,
 'ball is': 1,
 'bird in': 2,
 'come to': 3,
 'cost 1500': 4,
 'doiggle hower': 5,
 'fish in': 6,
 'goes to': 7,
 'good things': 8,
 'han is': 9,
 'in han': 10,
 'in the': 11,
 'in your': 12,
 'is in': 13,
 'is worth': 14,
 'mr smith': 15,
 'other fish': 16,
 'smith goes': 17,
 'the ball': 18,
 'the bush': 19,
 'the sea': 20,
 'there are': 21,
 'these watches': 22,
 'things come': 23,
 'those who': 24,
 'to those': 25,
 'to washigton': 26,
 'two in': 27,
 'watches cost': 28,
 'who wait': 29,
 'worth two': 30,
 'your court': 31}

In [ ]:
transformed_vector_n.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
from nltk import bigrams
from nltk import trigrams
from nltk.tokenize import word_tokenize

## **Bag of Words using TFIDF**

## **STOP WORD REMOVAL**

In [ ]:
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
print(stopwords.fileids())

['arabic', 'azerbaijani', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'turkish']


In [ ]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
text_array = ["A bird in hand is worth two in the bush.",
              "Good things come to those who wait.",
              "These watches cost $1500!",
              "There are other fish in the sea.",
              "The ball is in your court.",
              "Mr. Smith goes to Washigton.",
              "Doiggle Hower M.C."
              ]

In [ ]:
# join all the sentences
text = " ".join(text_array)

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
word_tokens = word_tokenize(text)

In [ ]:
stop_words = set(stopwords.words('english'))

filtered_words = []

for word in word_tokens:
  if word not in stop_words:
    filtered_words.append(word)

print(filtered_words)

['A', 'bird', 'hand', 'worth', 'two', 'bush', '.', 'Good', 'things', 'come', 'wait', '.', 'These', 'watches', 'cost', '$', '1500', '!', 'There', 'fish', 'sea', '.', 'The', 'ball', 'court', '.', 'Mr.', 'Smith', 'goes', 'Washigton', '.', 'Doiggle', 'Hower', 'M.C', '.']


In [ ]:
with open ("./file.txt", "w") as f:
  for word in filtered_words:
    f.write(word)
    f.write(' ')

In [ ]:
with open("./file.txt", "r") as f:
  file_contents = f.read()

print(file_contents)

A bird hand worth two bush . Good things come wait . These watches cost $ 1500 ! There fish sea . The ball court . Mr. Smith goes Washigton . Doiggle Hower M.C . 


In [ ]:
# Bag of Words representation of our text data

from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
count_vectorizer.fit([file_contents])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
transformed_vector = count_vectorizer.transform(text_array)

print(transformed_vector.shape)

(7, 25)


In [ ]:
feature_names_nltk = count_vectorizer.get_feature_names()

In [ ]:
count_vectorizer.vocabulary_

{'1500': 0,
 'ball': 1,
 'bird': 2,
 'bush': 3,
 'come': 4,
 'cost': 5,
 'court': 6,
 'doiggle': 7,
 'fish': 8,
 'goes': 9,
 'good': 10,
 'hand': 11,
 'hower': 12,
 'mr': 13,
 'sea': 14,
 'smith': 15,
 'the': 16,
 'there': 17,
 'these': 18,
 'things': 19,
 'two': 20,
 'wait': 21,
 'washigton': 22,
 'watches': 23,
 'worth': 24}

In [ ]:
print(transformed_vector.toarray())

[[0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
count_vectorizer.inverse_transform(transformed_vector)

[array(['bird', 'bush', 'hand', 'the', 'two', 'worth'], dtype='<U9'),
 array(['come', 'good', 'things', 'wait'], dtype='<U9'),
 array(['1500', 'cost', 'these', 'watches'], dtype='<U9'),
 array(['fish', 'sea', 'the', 'there'], dtype='<U9'),
 array(['ball', 'court', 'the'], dtype='<U9'),
 array(['goes', 'mr', 'smith', 'washigton'], dtype='<U9'),
 array(['doiggle', 'hower'], dtype='<U9')]

## **Frequency Filtering**

In [ ]:
from sklearn.datasets import fetch_20newsgroups

newsgropus = fetch_20newsgroups(subset='train')

In [ ]:
newsgropus.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [ ]:
newsgropus.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
count_vectorizer = CountVectorizer()
transformed_vector = count_vectorizer.fit_transform(newsgropus.data)

transformed_vector.shape

(11314, 130107)

In [ ]:
count_vectorizer = CountVectorizer(min_df = 0.0, max_df = 0.7)
transformed_vector = count_vectorizer.fit_transform(newsgropus.data)

transformed_vector.shape

(11314, 130094)

In [ ]:
count_vectorizer = CountVectorizer(min_df = 2, max_df = 100)
transformed_vector = count_vectorizer.fit_transform(newsgropus.data)

transformed_vector.shape

(11314, 54030)

## **STEMMING**

In [ ]:
from nltk import word_tokenize
from nltk.stem import *

import pandas as pd

In [ ]:
input_tokens = ['overwhelming','overwhelmingly','hushed','hush','functional','functionally','lying','lied','fairly','denstabilize','stability','the','these','those']

In [ ]:
ps = PorterStemmer()

ps_stemmed_tokens = []
for token in input_tokens:
  ps_stemmed_tokens.append(ps.stem(token))

In [ ]:
stems_df = pd.DataFrame({
    'words' : input_tokens,
    'Porter Stemmer' : ps_stemmed_tokens
})

stems_df

words  Porter Stemmer
0     overwhelming       overwhelm
1   overwhelmingly  overwhelmingli
2           hushed            hush
3             hush            hush
4       functional        function
5     functionally        function
6            lying             lie
7             lied             lie
8           fairly          fairli
9     denstabilize       denstabil
10       stability          stabil
11             the             the
12           these           these
13           those           those

In [ ]:
ls = LancasterStemmer()

ls_stemmed_tokens = []
for token in input_tokens:
  ls_stemmed_tokens.append(ls.stem(token))

stems_df_ls = pd.DataFrame({
  'words' : input_tokens,
  'Lancaster Stemmer' : ls_stemmed_tokens
})

stems_df_ls

words Lancaster Stemmer
0     overwhelming         overwhelm
1   overwhelmingly         overwhelm
2           hushed              hush
3             hush              hush
4       functional             funct
5     functionally             funct
6            lying             lying
7             lied              lied
8           fairly              fair
9     denstabilize             denst
10       stability             stabl
11             the               the
12           these              thes
13           those              thos

## **Lemmatization**

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
print(stemmer.stem('definitions'))

definit


In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
from nltk.stem import WordNetLemmatizer

wml = WordNetLemmatizer()
print(wml.lemmatize('definitions'))

definition


# **Part Of Speech**

In [ ]:
nltk.download('tagsets')

[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets.zip.


True

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
text = "I refuse to let this refuse get me down"

In [ ]:
tokenize_words = word_tokenize(text)
tagged_words = nltk.pos_tag(tokenize_words)
tagged_words

[('I', 'PRP'),
 ('refuse', 'VBP'),
 ('to', 'TO'),
 ('let', 'VB'),
 ('this', 'DT'),
 ('refuse', 'NN'),
 ('get', 'VB'),
 ('me', 'PRP'),
 ('down', 'RP')]

## **HASHING**

In [ ]:
from sklearn.feature_extraction import FeatureHasher

In [ ]:
text_array

['A bird in hand is worth two in the bush.',
 'Good things come to those who wait.',
 'These watches cost $1500!',
 'There are other fish in the sea.',
 'The ball is in your court.',
 'Mr. Smith goes to Washigton.',
 'Doiggle Hower M.C.']

In [ ]:
hasher = FeatureHasher(n_features=16, input_type='string')
hashed_features = hasher.fit_transform(text_array)

hashed_features.shape

(7, 16)

In [ ]:
hashed_features.toarray()

array([[ 1.,  0.,  1.,  1., -3., -4.,  0.,  1.,  9.,  0.,  0.,  0.,  0.,
        -7.,  1., -2.],
       [ 0., -3.,  1.,  3., -1., -2.,  0.,  2.,  6.,  1., -1.,  0.,  1.,
        -4.,  0., -2.],
       [ 0., -5.,  1., -1.,  2.,  1.,  0.,  3.,  3.,  0.,  0.,  0.,  0.,
        -4.,  0., -3.],
       [ 0.,  3.,  2., -1., -1., -2.,  0.,  6.,  6.,  0.,  0.,  1.,  0.,
        -6.,  0., -2.],
       [ 2.,  1.,  1.,  1., -1., -2.,  1.,  1.,  5.,  0.,  0.,  0.,  2.,
        -4.,  0., -1.],
       [-1.,  1.,  1.,  0., -1., -2.,  0.,  1.,  4.,  0., -1.,  0.,  0.,
        -4.,  0., -2.],
       [ 0.,  0.,  0.,  2.,  0., -2.,  1.,  2.,  2.,  1., -1.,  0.,  1.,
        -2.,  0.,  0.]])

## **Vectorizing Text Data and Dimensonality reduction**



In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

text_array

['A bird in hand is worth two in the bush.',
 'Good things come to those who wait.',
 'These watches cost $1500!',
 'There are other fish in the sea.',
 'The ball is in your court.',
 'Mr. Smith goes to Washigton.',
 'Doiggle Hower M.C.']

In [ ]:
count_vectorizer = CountVectorizer()
feature_vector = count_vectorizer.fit_transform(text_array)

feature_vector.shape

(7, 33)

In [ ]:
analyzer = count_vectorizer.build_analyzer()

word_tokens = analyzer(text_array[0])

word_tokens

['bird', 'in', 'hand', 'is', 'worth', 'two', 'in', 'the', 'bush']

In [ ]:
frequency_list = []

for i, text in enumerate(text_array):
  tokens = analyzer(text)

  word_frequency = {}

  for token in tokens:
    word_idx = count_vectorizer.vocabulary_[token]

    word_frequency[token] = feature_vector[i, word_idx]

  frequency_list.append(word_frequency)

In [ ]:
frequency_list

[{'bird': 1,
  'bush': 1,
  'hand': 1,
  'in': 2,
  'is': 1,
  'the': 1,
  'two': 1,
  'worth': 1},
 {'come': 1, 'good': 1, 'things': 1, 'those': 1, 'to': 1, 'wait': 1, 'who': 1},
 {'1500': 1, 'cost': 1, 'these': 1, 'watches': 1},
 {'are': 1, 'fish': 1, 'in': 1, 'other': 1, 'sea': 1, 'the': 1, 'there': 1},
 {'ball': 1, 'court': 1, 'in': 1, 'is': 1, 'the': 1, 'your': 1},
 {'goes': 1, 'mr': 1, 'smith': 1, 'to': 1, 'washigton': 1},
 {'doiggle': 1, 'hower': 1}]

In [ ]:
hasher = FeatureHasher(n_features=8, input_type='string')
hashed_features = hasher.fit_transform(frequency_list)

hashed_features.shape

(7, 8)

In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer

hasher = FeatureHasher(n_features=8, input_type='string')
hashed_features = hasher.fit_transform(text_array)

hashed_features.shape

(7, 8)

## **Locality Sensetive hashing**

In [ ]:
!pip install datasketch

     |████████████████████████████████| 67 kB 3.0 MB/s 


In [ ]:
from datasketch import MinHash, MinHashLSH

from nltk import ngrams
from nltk import word_tokenize

In [ ]:
text_array.append('the ball ix in the court le')

In [ ]:
word_token_array = [word_tokenize(text) for text in text_array]
word_token_array

[['A', 'bird', 'in', 'hand', 'is', 'worth', 'two', 'in', 'the', 'bush', '.'],
 ['Good', 'things', 'come', 'to', 'those', 'who', 'wait', '.'],
 ['These', 'watches', 'cost', '$', '1500', '!'],
 ['There', 'are', 'other', 'fish', 'in', 'the', 'sea', '.'],
 ['The', 'ball', 'is', 'in', 'your', 'court', '.'],
 ['Mr.', 'Smith', 'goes', 'to', 'Washigton', '.'],
 ['Doiggle', 'Hower', 'M.C', '.'],
 ['the', 'ball', 'ix', 'in', 'the', 'court', 'le']]

In [ ]:
for index, word_token in enumerate(word_token_array):
  for n_gram in ngrams(word_token, 3):
    print(index, n_gram)

0 ('A', 'bird', 'in')
0 ('bird', 'in', 'hand')
0 ('in', 'hand', 'is')
0 ('hand', 'is', 'worth')
0 ('is', 'worth', 'two')
0 ('worth', 'two', 'in')
0 ('two', 'in', 'the')
0 ('in', 'the', 'bush')
0 ('the', 'bush', '.')
1 ('Good', 'things', 'come')
1 ('things', 'come', 'to')
1 ('come', 'to', 'those')
1 ('to', 'those', 'who')
1 ('those', 'who', 'wait')
1 ('who', 'wait', '.')
2 ('These', 'watches', 'cost')
2 ('watches', 'cost', '$')
2 ('cost', '$', '1500')
2 ('$', '1500', '!')
3 ('There', 'are', 'other')
3 ('are', 'other', 'fish')
3 ('other', 'fish', 'in')
3 ('fish', 'in', 'the')
3 ('in', 'the', 'sea')
3 ('the', 'sea', '.')
4 ('The', 'ball', 'is')
4 ('ball', 'is', 'in')
4 ('is', 'in', 'your')
4 ('in', 'your', 'court')
4 ('your', 'court', '.')
5 ('Mr.', 'Smith', 'goes')
5 ('Smith', 'goes', 'to')
5 ('goes', 'to', 'Washigton')
5 ('to', 'Washigton', '.')
6 ('Doiggle', 'Hower', 'M.C')
6 ('Hower', 'M.C', '.')
7 ('the', 'ball', 'ix')
7 ('ball', 'ix', 'in')
7 ('ix', 'in', 'the')
7 ('in', 'the', 'cou

In [ ]:
min_hash_lsh = MinHashLSH(threshold = 0.5, num_perm=128)

In [ ]:
min_hashes = {}

for index, text in enumerate(text_array):
  min_hash = MinHash(num_perm=128)

  for n_gram in ngrams(text, 3):
    min_hash.update("".join(n_gram).encode('utf-8'))

  min_hash_lsh.insert(index, min_hash)
  min_hashes[index] = min_hash 

In [ ]:
min_hashes

{0: <datasketch.minhash.MinHash at 0x7fab709bfc50>,
 1: <datasketch.minhash.MinHash at 0x7fab70878b10>,
 2: <datasketch.minhash.MinHash at 0x7fab70878ed0>,
 3: <datasketch.minhash.MinHash at 0x7fab70878050>,
 4: <datasketch.minhash.MinHash at 0x7fab69c8e590>,
 5: <datasketch.minhash.MinHash at 0x7fab7176a310>,
 6: <datasketch.minhash.MinHash at 0x7fab70878b90>,
 7: <datasketch.minhash.MinHash at 0x7fab708b9f50>}

In [ ]:
for i in min_hashes.keys():
  result = min_hash_lsh.query(min_hashes[i])
  print("candiadte paired with jaccard similarity > 0.5 for input", i, ":", result)

candiadte paired with jaccard similarity > 0.5 for input 0 : [0]
candiadte paired with jaccard similarity > 0.5 for input 1 : [1]
candiadte paired with jaccard similarity > 0.5 for input 2 : [2]
candiadte paired with jaccard similarity > 0.5 for input 3 : [3]
candiadte paired with jaccard similarity > 0.5 for input 4 : [4]
candiadte paired with jaccard similarity > 0.5 for input 5 : [5]
candiadte paired with jaccard similarity > 0.5 for input 6 : [6]
candiadte paired with jaccard similarity > 0.5 for input 7 : [7]


## **HashingVectorize_NaiveBayesClassifier**

In [ ]:
import pandas as pandas
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.naive_bayes import Gauss

ImportError: ignored

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test (2).csv


KeyboardInterrupt: ignored

In [ ]:
import io
df = pd.read_csv(io.StringIO(uploaded['test.csv'].decode('utf-8')), skiprows = 1, names = ['Label', 'Name', 'Text'])
df.head()

In [ ]:
df.shape

In [ ]:
df = df.sample(10000, replace= False)

In [ ]:
X = df['Text']
Y = df['Label']

In [ ]:
X.head()

60633     Anomalías eléctricas is a 2010 short animated...
55744     Player (stylised PLAYER) is the eleventh stud...
35108     The Berzunți River is a tributary of the More...
60119     Dillinger is a 1945 gangster film telling the...
1356      Hertel Wax is an American company which produ...
Name: Text, dtype: object

In [ ]:
Y.head()

60633    13
55744    12
35108     8
60119    13
1356      1
Name: Label, dtype: int64

In [ ]:
def summarize_classification(y_test, y_pred):

  acc = accuracy_score(y_test, y_pred, normalize=True)
  num_acc = accuracy_score(y_test, y_pred, normalize=False)
  prec = precision_score(y_test, y_pred, average='weighted')
  recall = recall_score(y_test, y_pred, average="weighted")

  print("Length of testing data: ", len(y_test))
  print("accuracy_count: ", num_acc)
  print("accuracy_score: ", prec)
  print("oPrecision score: ", prec)
  print("recall_score: ", recall)

In [ ]:
vectorizer = HashingVectorizer(n_features=2**10, norm='l2')

feature_vector = vectorizer.transform(X)

feature_vector.shape

(10000, 1024)

In [ ]:
X_dense = feature_vector.todense()

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)

In [ ]:
clf = GaussianNB().fit(x_train, y_train)

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([8, 1, 3, ..., 5, 5, 7])

In [ ]:
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1144
accuracy_score:  0.5841193145448108
recall_score:  0.572


## **Stemmer_HashingVectorize_NaiveBayesClassisfier**

In [ ]:
from nltk.stem.snowball import SnowballStemmer

In [ ]:
stemmer = SnowballStemmer('english')
analyzer = HashingVectorizer().build_analyzer()

In [ ]:
def stemmed_words(doc):
  return [stemmer.stem(w) for w in analyzer(doc)]

In [ ]:
stem_vectorizer = HashingVectorizer(n_features=2**10, norm='l2', analyzer=stemmed_words)
feature_vector = stem_vectorizer.transform(X)

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1098
accuracy_score:  0.5684109110532525
recall_score:  0.549


## **CountVectorizer_NaiveBayesClassifier**

In [ ]:
count_vectorizer = CountVectorizer()
feature_vector = count_vectorizer.fit_transform(X)

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1465
accuracy_score:  0.7441069162662086
oPrecision score:  0.7441069162662086
recall_score:  0.7325


## **StopWord_removal_CountVectorizer_NaiveBayesClassifier**

In [ ]:
count_vectorizer = CountVectorizer(stop_words='english')
feature_vector = count_vectorizer.fit_transform(X)

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1470
accuracy_score:  0.7469763496088342
oPrecision score:  0.7469763496088342
recall_score:  0.735


## **StopWordRemoval_FrequencyFiltering_CountVectorizer_NaiveBayesClassifier**

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from sklearn.feature_extraction import text

In [ ]:
tokens = word_tokenize("\n".join(X.values))


In [ ]:

freq = FreqDist(tokens)

In [ ]:
frequent_words = []

for key, value in freq.items():
  if value >= 100:
    frequency_list.append(key.lower())

print(len(frequency_list))

1963


In [ ]:
stop_words = text.ENGLISH_STOP_WORDS.union(frequent_words)

In [ ]:
count_vectorizer = CountVectorizer(stop_words=stop_words)
feature_vector = count_vectorizer.fit_transform(X)

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1496
accuracy_score:  0.7554031577938128
oPrecision score:  0.7554031577938128
recall_score:  0.748


## **TfIDFVectorize_NaiveBayesClassifier**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
count_vectorizer = TfidfVectorizer()
feature_vector = count_vectorizer.fit_transform(X)

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)

Length of testing data:  2000
accuracy_count:  1408
accuracy_score:  0.7166636116465238
oPrecision score:  0.7166636116465238
recall_score:  0.704


## **BiGrams_CountVectorizer_NaiveBayesClassifier**

In [ ]:
count_vectorizer = CountVectorizer(ngram_range=(2,2))
feature_vector = count_vectorizer.fit_transform(X)

NameError: ignored

In [ ]:
X_dense = feature_vector.todense()
x_train, x_test, y_train, y_test= train_test_split(X_dense, Y, test_size=0.2)
clf = GaussianNB().fit(x_train, y_train)
y_pred = clf.predict(x_test)
summarize_classification(y_test, y_pred)